/// @description Insert description here
scr_singleton();

enemyArray[0,0] = noone; // row to spawn on
enemyArray[0,1] = noone; // enemy type
enemyArray[1,0] = 0; // row to spawn on
enemyArray[1,1] = 0; // enemy type
enemyArray[2,0] = noone; // row to spawn on
enemyArray[2,1] = 1; // enemy type
enemyArray[3,0] = 1; // row to spawn on
enemyArray[3,1] = 1; // enemy type
enemyArray[4,0] = 2; // row to spawn on
enemyArray[4,1] = 0; // enemy type
enemyArray[5,0] = 0; // row to spawn on
enemyArray[5,1] = 2; // enemy type
enemyArray[6,0] = 2; // row to spawn on
enemyArray[6,1] = 0; // enemy type
enemyArray[7,0] = 1; // row to spawn on
enemyArray[7,1] = 1; // enemy type
enemyArray[8,0] = 1; // row to spawn on
enemyArray[8,1] = 0; // enemy type
enemyArray[9,0] = 2; // row to spawn on
enemyArray[9,1] = 2; // enemy type
enemyArray[10,0] = 0; // row to spawn on
enemyArray[10,1] = 1; // enemy type
enemyArray[11,0] = 2; // row to spawn on
enemyArray[11,1] = 2; // enemy type
enemyArray[12,0] = 1; // row to spawn on
enemyArray[12,1] = 0; // enemy type
enemyArray[13,0] = 1; // row to spawn on
enemyArray[13,1] = 0; // enemy type
enemyArray[14,0] = 0; // row to spawn on
enemyArray[14,1] = 2; // enemy type
enemyArray[15,0] = 0; // row to spawn on
enemyArray[15,1] = 1; // enemy type
enemyArray[16,0] = 1; // row to spawn on
enemyArray[16,1] = 0; // enemy type
enemyArray[17,0] = 2; // row to spawn on
enemyArray[17,1] = 0; // enemy type
enemyArray[18,0] = 2; // row to spawn on
enemyArray[18,1] = 1; // enemy type
enemyArray[19,0] = 1; // row to spawn on
enemyArray[19,1] = 0; // enemy type
enemyArray[20,0] = 0; // row to spawn on
enemyArray[20,1] = 2; // enemy type
enemyArray[21,0] = 0; // row to spawn on
enemyArray[21,1] = 1; // enemy type
enemyArray[22,0] = 2; // row to spawn on
enemyArray[22,1] = 2; // enemy type
enemyArray[23,0] = 1; // row to spawn on
enemyArray[23,1] = 0; // enemy type
enemyArray[24,0] = 0; // row to spawn on
enemyArray[24,1] = 1; // enemy type
enemyArray[25,0] = 0; // row to spawn on
enemyArray[25,1] = 1; // enemy type
enemyArray[26,0] = 2; // row to spawn on
enemyArray[26,1] = 1; // enemy type
enemyArray[27,0] = 2; // row to spawn on
enemyArray[27,1] = 1; // enemy type
enemyArray[28,0] = 2; // row to spawn on
enemyArray[28,1] = 0; // enemy type
enemyArray[29,0] = 1; // row to spawn on
enemyArray[29,1] = 2; // enemy type
enemyArray[30,0] = noone; // row to spawn on
enemyArray[30,1] = noone; // enemy type
enemyArray[31,0] = noone; // row to spawn on
enemyArray[31,1] = noone; // enemy type
enemyArray[32,0] = noone; // row to spawn on
enemyArray[32,1] = noone; // enemy type
enemyArray[33,0] = noone; // row to spawn on
enemyArray[33,1] = noone; // enemy type
enemyArray[34,0] = 1; // row to spawn on
enemyArray[34,1] = -1; // enemy type



